'use client';
import { useState } from 'react';

type RewardConfig={min_withdraw_points:number;points_per_rupiah:number;min_correct_for_withdraw:number;daily_quiz_reward_cap:number};
type AdsConfig={rewarded_enabled:boolean;reward_kind:'HINT'|'TICKET'|'XP';reward_amount:number;daily_rewarded_cap:number};
export default function SettingsForm({config,adsConfig}:{config:RewardConfig;adsConfig:AdsConfig}){
 const [rewardMsg,setRewardMsg]=useState(''); const [adsMsg,setAdsMsg]=useState('');
 async function saveReward(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setRewardMsg('');const f=new FormData(e.currentTarget);const body={min_withdraw_points:Number(f.get('min')),points_per_rupiah:Number(f.get('ratio')),min_correct_for_withdraw:Number(f.get('correct')),daily_quiz_reward_cap:Number(f.get('cap'))};const r=await fetch('/api/admin/settings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});setRewardMsg(r.ok?'Tersimpan':(await r.json()).error||'Gagal')}
 async function saveAds(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setAdsMsg('');const f=new FormData(e.currentTarget);const body={rewarded_enabled:f.get('enabled')==='on',reward_kind:String(f.get('kind')),reward_amount:Number(f.get('amount')),daily_rewarded_cap:Number(f.get('dailyCap'))};const r=await fetch('/api/admin/ads-settings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});setAdsMsg(r.ok?'Tersimpan':(await r.json()).error||'Gagal')}
 return <div className="stack">
  <form className="card stack" onSubmit={saveReward}><h2>Redeemable economy</h2><p className="muted">Pengaturan ini memengaruhi poin yang dapat ditarik menjadi rupiah.</p><label>Minimum withdraw (poin)<input name="min" type="number" min="1" defaultValue={config.min_withdraw_points}/></label><label>Poin per Rp1<input name="ratio" type="number" min="1" defaultValue={config.points_per_rupiah}/></label><label>Minimal jawaban benar sebelum withdraw<input name="correct" type="number" min="0" defaultValue={config.min_correct_for_withdraw}/></label><label>Batas reward quiz / hari<input name="cap" type="number" min="1" defaultValue={config.daily_quiz_reward_cap}/></label><button className="primary">Simpan Reward Economy</button><p aria-live="polite">{rewardMsg}</p></form>
  <form className="card stack" onSubmit={saveAds}><h2>Rewarded Ads</h2><p className="muted">Reward iklan bersifat non-tunai dan tidak masuk ke saldo poin redeemable.</p><label><input name="enabled" type="checkbox" defaultChecked={adsConfig.rewarded_enabled}/> Rewarded ads aktif</label><label>Jenis reward<select name="kind" defaultValue={adsConfig.reward_kind}><option value="TICKET">Ticket</option><option value="HINT">Hint</option><option value="XP">XP</option></select></label><label>Reward per verifikasi<input name="amount" type="number" min="1" max="100" defaultValue={adsConfig.reward_amount}/></label><label>Batas reward terverifikasi / hari<input name="dailyCap" type="number" min="1" max="100" defaultValue={adsConfig.daily_rewarded_cap}/></label><button className="primary">Simpan Ads Settings</button><p aria-live="polite">{adsMsg}</p></form>
 </div>
}
