-- KuisPoin v0.6 question bank. Idempotent: skips duplicate question_text.
DO $$
DECLARE qz UUID; rec RECORD; qid UUID;
BEGIN
 SELECT id INTO qz FROM quizzes WHERE is_active=TRUE ORDER BY created_at LIMIT 1;
 IF qz IS NULL THEN RAISE EXCEPTION 'Tidak ada quiz aktif. Jalankan seed.sql lebih dulu.'; END IF;
 FOR rec IN SELECT * FROM (VALUES
('Ibu kota Indonesia saat ini secara konstitusional adalah?','Jakarta','Bandung','Surabaya','Medan',1),
('Planet terbesar di Tata Surya adalah?','Mars','Jupiter','Venus','Merkurius',2),
('Hasil 12 × 8 adalah?','86','96','108','88',2),
('Air membeku pada suhu berapa derajat Celsius?','0','10','32','100',1),
('Benua terluas di dunia adalah?','Afrika','Asia','Eropa','Amerika Selatan',2),
('Bahasa yang berjalan di browser secara native adalah?','PHP','JavaScript','Go','Python',2),
('Protokol aman untuk mengakses website adalah?','FTP','HTTP','HTTPS','SMTP',3),
('CPU merupakan singkatan dari?','Central Processing Unit','Computer Personal Unit','Core Process Utility','Central Program User',1),
('Mamalia terbesar di dunia adalah?','Gajah Afrika','Paus biru','Jerapah','Hiu paus',2),
('Gunung tertinggi di dunia di atas permukaan laut adalah?','K2','Everest','Kilimanjaro','Fuji',2),
('Hasil 15 + 27 adalah?','32','42','52','38',2),
('Hasil 144 ÷ 12 adalah?','10','11','12','14',3),
('Akar kuadrat dari 81 adalah?','7','8','9','10',3),
('25% dari 200 adalah?','25','40','50','75',3),
('Bilangan prima di antara pilihan berikut adalah?','21','27','29','33',3),
('Satuan SI untuk panjang adalah?','Liter','Meter','Gram','Detik',2),
('Satuan SI untuk massa adalah?','Kilogram','Newton','Meter','Watt',1),
('Organ utama pernapasan manusia adalah?','Jantung','Ginjal','Paru-paru','Lambung',3),
('Fotosintesis terutama berlangsung pada bagian sel tumbuhan bernama?','Nukleus','Kloroplas','Ribosom','Mitokondria',2),
('Gas yang paling banyak terdapat di atmosfer Bumi adalah?','Oksigen','Karbon dioksida','Nitrogen','Hidrogen',3),
('Samudra terluas di dunia adalah?','Atlantik','Hindia','Pasifik','Arktik',3),
('Negara dengan wilayah terluas di dunia adalah?','Kanada','China','Rusia','Amerika Serikat',3),
('Mata uang Jepang adalah?','Won','Yuan','Yen','Baht',3),
('Candi Borobudur berada di provinsi?','Jawa Tengah','Jawa Timur','Bali','DI Yogyakarta',1),
('Danau Toba berada di provinsi?','Sumatera Barat','Sumatera Utara','Aceh','Riau',2),
('Proklamasi Kemerdekaan Indonesia dibacakan pada?','17 Agustus 1945','1 Juni 1945','28 Oktober 1928','10 November 1945',1),
('Semboyan Bhinneka Tunggal Ika berarti?','Bersatu kita teguh','Berbeda-beda tetapi tetap satu','Merdeka atau mati','Gotong royong',2),
('Pulau terbesar yang seluruh wilayahnya berada di Indonesia adalah?','Jawa','Sulawesi','Sumatra','Bali',3),
('Kota yang dikenal sebagai Kota Pahlawan adalah?','Bandung','Surabaya','Semarang','Makassar',2),
('Komodo secara alami terkenal berasal dari provinsi?','NTT','NTB','Bali','Maluku',1),
('HTML digunakan terutama untuk?','Mengatur struktur halaman web','Mengelola database','Mengompilasi kernel','Mengirim email',1),
('CSS digunakan terutama untuk?','Autentikasi','Styling tampilan web','Database query','Enkripsi',2),
('SQL digunakan untuk?','Mengedit gambar','Berinteraksi dengan basis data relasional','Membuat animasi 3D','Mengompresi video',2),
('HTTP status 404 umumnya berarti?','Berhasil','Unauthorized','Not Found','Server Error',3),
('HTTP status 500 menunjukkan?','Redirect','Kesalahan server','Resource dibuat','Forbidden',2),
('Git digunakan terutama untuk?','Version control','Video editing','Spreadsheet','DNS hosting',1),
('Perintah Git untuk membuat salinan repository adalah?','git push','git clone','git merge','git status',2),
('JSON merupakan format yang umum digunakan untuk?','Pertukaran data','Kompresi gambar','Audio streaming saja','Mencetak dokumen',1),
('API merupakan singkatan dari?','Application Programming Interface','Automatic Program Internet','Applied Protocol Integration','Application Process Internet',1),
('Database PostgreSQL termasuk jenis?','Relasional','Grafis saja','Spreadsheet','Text editor',1),
('RAM pada komputer terutama digunakan sebagai?','Penyimpanan sementara saat program berjalan','Penyimpanan arsip permanen','Perangkat input','Kartu jaringan',1),
('SSD digunakan untuk?','Penyimpanan data','Menampilkan gambar','Mengukur suhu','Menghubungkan printer saja',1),
('DNS berfungsi untuk?','Menerjemahkan nama domain ke alamat IP','Mengenkripsi hard disk','Mengedit HTML','Menyimpan password browser',1),
('IP adalah singkatan dari?','Internet Protocol','Internal Program','Input Process','Integrated Port',1),
('Sistem operasi open-source yang populer adalah?','Linux','Photoshop','Chrome','Excel',1),
('Next.js dibangun di atas library?','React','Laravel','Django','Flutter',1),
('Supabase menggunakan database utama?','MongoDB','PostgreSQL','SQLite saja','Redis',2),
('TypeScript merupakan superset dari?','Java','JavaScript','Python','C#',2),
('Node.js memungkinkan JavaScript berjalan terutama di?','Server/runtime di luar browser','Database SQL saja','BIOS','GPU saja',1),
('REST API umumnya menggunakan protokol?','HTTP','Bluetooth','HDMI','SMTP saja',1),
('Kecepatan cahaya kira-kira adalah?','300.000 km/s','30.000 km/s','3.000 km/s','3 juta km/s',1),
('Planet yang dikenal sebagai Planet Merah adalah?','Mars','Saturnus','Neptunus','Venus',1),
('Satelit alami Bumi adalah?','Matahari','Bulan','Mars','Venus',2),
('H2O adalah rumus kimia untuk?','Oksigen','Air','Garam','Karbon dioksida',2),
('Simbol kimia emas adalah?','Ag','Au','Fe','Cu',2),
('Jumlah kromosom normal pada sel tubuh manusia adalah?','23','46','44','48',2),
('Jantung manusia normal memiliki berapa ruang?','2','3','4','5',3),
('Vitamin yang banyak dibentuk tubuh dengan bantuan sinar matahari adalah?','Vitamin A','Vitamin B12','Vitamin C','Vitamin D',4),
('Hewan yang mengalami metamorfosis dari ulat adalah?','Kupu-kupu','Kucing','Ayam','Ikan',1),
('Tumbuhan menyerap air terutama melalui?','Daun','Bunga','Akar','Buah',3),
('1 kilometer sama dengan berapa meter?','100','500','1.000','10.000',3),
('1 jam sama dengan berapa menit?','30','60','90','100',2),
('Keliling persegi dengan sisi 5 cm adalah?','10 cm','20 cm','25 cm','15 cm',2),
('Luas persegi dengan sisi 6 cm adalah?','12 cm²','24 cm²','36 cm²','42 cm²',3),
('Jika 3x = 21, nilai x adalah?','6','7','8','9',2),
('Hasil 2 pangkat 5 adalah?','10','16','25','32',4),
('Rata-rata dari 4, 6, dan 8 adalah?','5','6','7','8',2),
('Pecahan 1/2 setara dengan?','25%','50%','75%','100%',2),
('Hasil 7 × 9 adalah?','56','63','72','69',2),
('Hasil 100 - 37 adalah?','53','63','73','67',2),
('Ibukota Jawa Barat adalah?','Bogor','Bandung','Bekasi','Cirebon',2),
('Ibukota Jawa Tengah adalah?','Solo','Semarang','Magelang','Tegal',2),
('Ibukota Jawa Timur adalah?','Malang','Surabaya','Kediri','Madiun',2),
('Selat yang memisahkan Pulau Jawa dan Sumatra adalah?','Selat Sunda','Selat Malaka','Selat Makassar','Selat Bali',1),
('Indonesia berada di antara Samudra Hindia dan?','Arktik','Pasifik','Atlantik','Selatan',2),
('ASEAN didirikan pada tahun?','1945','1967','1975','1998',2),
('Lambang negara Indonesia adalah?','Garuda Pancasila','Rajawali Nusantara','Elang Jawa','Harimau Sumatra',1),
('Jumlah sila dalam Pancasila adalah?','3','4','5','6',3),
('Warna bendera Indonesia adalah?','Merah dan putih','Merah dan biru','Putih dan hijau','Biru dan putih',1),
('Hari Sumpah Pemuda diperingati setiap?','17 Agustus','1 Juni','28 Oktober','10 November',3)
) AS v(question_text,a,b,c,d,correct_pos) LOOP
  IF NOT EXISTS(SELECT 1 FROM questions WHERE quiz_id=qz AND question_text=rec.question_text) THEN
   INSERT INTO questions(quiz_id,question_text,position) VALUES(qz,rec.question_text,(SELECT COALESCE(MAX(position),0)+1 FROM questions WHERE quiz_id=qz)) RETURNING id INTO qid;
   INSERT INTO question_options(question_id,option_text,is_correct,position) VALUES
    (qid,rec.a,rec.correct_pos=1,1),(qid,rec.b,rec.correct_pos=2,2),(qid,rec.c,rec.correct_pos=3,3),(qid,rec.d,rec.correct_pos=4,4);
  END IF;
 END LOOP;
END $$;
