import { NextResponse } from 'next/server';
import { requireAdmin, audit } from '@/lib/admin';
import { supabaseAdmin } from '@/lib/supabase-admin';
export async function POST(req:Request){
 const s=await requireAdmin(); if(!s) return NextResponse.json({error:'Forbidden'},{status:403});
 const b=await req.json().catch(()=>null); const cfg={enabled:Boolean(b?.enabled),referrer_reward_points:Number(b?.referrer_reward_points),referred_reward_points:Number(b?.referred_reward_points),min_account_age_hours:Number(b?.min_account_age_hours),min_completed_quizzes:Number(b?.min_completed_quizzes),max_qualified_per_referrer_30d:Number(b?.max_qualified_per_referrer_30d),attribution_window_days:Number(b?.attribution_window_days)};
 if(!Number.isInteger(cfg.referrer_reward_points)||cfg.referrer_reward_points<0||cfg.referrer_reward_points>100000||!Number.isInteger(cfg.referred_reward_points)||cfg.referred_reward_points<0||cfg.referred_reward_points>100000||!Number.isInteger(cfg.min_account_age_hours)||cfg.min_account_age_hours<0||cfg.min_account_age_hours>720||!Number.isInteger(cfg.min_completed_quizzes)||cfg.min_completed_quizzes<1||cfg.min_completed_quizzes>100||!Number.isInteger(cfg.max_qualified_per_referrer_30d)||cfg.max_qualified_per_referrer_30d<1||cfg.max_qualified_per_referrer_30d>1000||!Number.isInteger(cfg.attribution_window_days)||cfg.attribution_window_days<1||cfg.attribution_window_days>30) return NextResponse.json({error:'Nilai referral tidak valid'},{status:400});
 const {error}=await supabaseAdmin.from('app_settings').upsert({key:'referral_config',value:cfg},{onConflict:'key'}); if(error)return NextResponse.json({error:'Gagal menyimpan'},{status:500}); await audit(s.user.id,'UPDATE_REFERRAL_SETTINGS','APP_SETTING','referral_config',cfg); return NextResponse.json({ok:true});
}
